name: GitHub Actions Demo
on: [push]
jobs:
Explore-GitHub-Actions:
runs-on: windows-latest    
        
steps:
- uses: actions/checkout@v2
with:
fetch-depth: 0    
uses: actions/setup-node@v1
with:
node-version: ${{ matrix.node-version }}
- run: git fetch origin main
- run: npm install
- name: Run Affected Tests
shell: bash
run: npm run affected:test -- --base=remotes/origin/main
