name: Movies test lint build deploy  
on: 
  push:
      branches: [main] 
jobs:
  build:
    runs-on: windows-latest
    defaults:  
      run:
       working-directory: hfmorg 
    strategy:
      matrix:
        node-version: [12.x]    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch origin main     
      - run: ls
      - run: npm install
      - name: Run Affected Tests
        shell: bash
        run: npm run affected:test -- --base=remotes/origin/main
      - name: Run Affected Lint
        shell: bash
        run: npm run affected:lint -- --base=remotes/origin/main  
      - run: npm run test movies
      - run: npm run lint movies
      - run: npm run build movies  
      - run: npm run deploy movies