name: Test and lint movies app on push to main
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    defaults:  
      run:
       working-directory: hfmorg 
    steps:         
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}    
      - run: nx test Movies
      - run: nx lint movies           
      - run: echo "🍏 This job's status is ${{ job.status }}."

